export const products = [
    {
        id: 1,
        name: "SNDW Bites Rebon Udang",
        tagline: "Gurih Laut yang Bikin Nagih",
        desc: "Kriuk renyah dengan cita rasa rebon udang asli pilihan. Gurih alami, ringan di mulut, berat di kantong karena selalu mau nambah!",
        price: 20000,
        image: "/product-rebon.jpeg",
        badge: "BESTSELLER",
        badgeColor: "#e74c3c",
        accent: "#ff6b35",
        features: ["Rebon udang asli", "Tanpa MSG berlebih", "Premium Quality"],
    },
    {
        id: 2,
        name: "SNDW Bites Kacang",
        tagline: "Kriuk Gurih Penuh Cita Rasa",
        desc: "Perpaduan sempurna kacang pilihan dengan bumbu rahasia SNDW. Teksturnya nendang, rasanya bikin senyum-senyum sendiri.",
        price: 20000,
        image: "/product-kacang.jpeg",
        badge: "FAVORIT",
        badgeColor: "#8bc34a",
        accent: "#8bc34a",
        features: ["Kacang pilihan", "Bumbu rahasia", "100% Indonesia"],
    },
];

export const testimonials = [
    { name: "Rina S.", loc: "Bandung", text: "Rebon udang-nya juara! Sekali makan langsung habis sebungkus. Udah order 5x minggu ini 😂", stars: 5 },
    { name: "Dimas P.", loc: "Jakarta", text: "Yang kacang beneran nagih, cocok banget buat nemenin kerja malam. Kriuk-nya awet!", stars: 5 },
    { name: "Siti N.", loc: "Surabaya", text: "Anak-anak sampe rebutan, packaging-nya juga lucu banget. Recommended!", stars: 5 },
    { name: "Bagas W.", loc: "Yogyakarta", text: "Beli buat oleh-oleh, eh malah diminta lagi sama yang dikasih. Sekarang rutin order tiap minggu!", stars: 5 },
    { name: "Farah A.", loc: "Bandung", text: "Nyoba karena direkomendasiin temen, langsung jatuh cinta sama varian rebonnya. Gurih banget!", stars: 5 },
    { name: "Kevin R.", loc: "Bekasi", text: "Snack paling worth it yang pernah gue coba. Harga segini buat kualitas kayak gini? Gila sih.", stars: 5 },
    { name: "Nadya K.", loc: "Depok", text: "Kriuknya beda dari snack lain, nggak gampang melempem. Udah seminggu masih kriuk!", stars: 5 },
    { name: "Rizky F.", loc: "Medan", text: "Pesan malem, besok pagi udah nyampe. Packaging rapi, snack-nya masih fresh. Top!", stars: 5 },
    { name: "Annisa M.", loc: "Semarang", text: "Varian kacangnya bikin ketagihan parah. Udah kasih tau semua orang kantor 😄", stars: 5 },
    { name: "Hendra S.", loc: "Bandung", text: "Awalnya ragu beli online, tapi pas nyoba langsung repeat order. Rasanya autentik banget!", stars: 5 },
    { name: "Putri L.", loc: "Bogor", text: "Cocok banget buat cemilan sore bareng teh hangat. Rebon udangnya gurih, nggak terlalu asin.", stars: 5 },
    { name: "Andi T.", loc: "Cimahi", text: "Udah cobain banyak snack lokal, SNDW Bites yang paling konsisten kualitasnya. Respect!", stars: 5 },
    { name: "Maya R.", loc: "Jakarta Selatan", text: "Pertama order 2 bungkus buat nyoba, sekarang tiap order minimal 10 bungkus. Ketagihan!", stars: 5 },
    { name: "Budi H.", loc: "Tangerang", text: "Dibawa ke kantor langsung ludes dalam 10 menit. Temen-temen pada minta link belinya 😂", stars: 5 },
    { name: "Dewi S.", loc: "Bandung Barat", text: "Anakku yang susah makan jajanan lokal malah doyan banget sama SNDW. Makasih ya!", stars: 5 },
    { name: "Gilang P.", loc: "Sukabumi", text: "Rasanya beda banget dari snack pabrik. Kerasa homemade-nya, bumbu meresap sempurna.", stars: 5 },
    { name: "Tari W.", loc: "Bandung", text: "Kemasan lucu, rasa nggak bohong. Varian rebon udang favorit keluarga besar kami!", stars: 5 },
    { name: "Ikhsan N.", loc: "Karawang", text: "Harga terjangkau tapi kualitasnya premium. Kalau ada bintang 6 pasti gue kasih!", stars: 5 },
    { name: "Lina K.", loc: "Purwakarta", text: "Snack pertama yang bikin suami aku ikut rebutan. Biasanya dia nggak suka ngemil!", stars: 5 },
    { name: "Reza M.", loc: "Jakarta Timur", text: "Packaging vakumnya bagus, nyampe masih renyah meski dikirim jauh. Top seller layak!", stars: 5 },
    { name: "Fitri A.", loc: "Subang", text: "Udah jadi camilan wajib WFH. Fokus kerja jadi lebih semangat kalau ada SNDW Bites 😄", stars: 5 },
    { name: "Eko B.", loc: "Cirebon", text: "Nemu SNDW waktu lagi cari snack sehat. Nggak nyesel sama sekali, jadi pelanggan tetap!", stars: 5 },
    { name: "Sari W.", loc: "Bandung", text: "Beli buat hantaran lebaran, penerimanya pada suka semua. Tahun depan pesen lagi!", stars: 5 },
    { name: "Doni F.", loc: "Garut", text: "Kacangnya crunchy banget, beda dari kacang snack biasa. Ada rasa rempahnya yang nendang!", stars: 5 },
    { name: "Nisa P.", loc: "Tasikmalaya", text: "Sempat takut pesan karena belum kenal, tapi setelah coba langsung jadi langganan tetap!", stars: 5 },
    { name: "Yudi A.", loc: "Bandung Timur", text: "Dikasih sama temen, langsung cari sendiri buat beli lagi. SNDW emang nggak ada duanya!", stars: 5 },
    { name: "Rini H.", loc: "Majalengka", text: "Snack lokal terenak yang pernah aku coba. Bangga produk Bandung kualitasnya sekeren ini!", stars: 5 },
    { name: "Agus S.", loc: "Cianjur", text: "Kriuknya tahan lama banget, udah seminggu lebih masih renyah. Packaging-nya memang juara.", stars: 5 },
    { name: "Wulan D.", loc: "Bandung", text: "Rebon udang sama kacang dua-duanya enak, susah milih favorit. Akhirnya beli dua varian sekaligus!", stars: 5 },
    { name: "Hafiz R.", loc: "Indramayu", text: "Pertama kali cobain langsung order lagi buat stok. Rasanya konsisten dari order pertama sampai sekarang!", stars: 5 },
];

export type Product = (typeof products)[0];
export type CartItem = { product: Product; qty: number };